"""Mapping utilities for reconciliation rules."""

from __future__ import annotations

CONCEPT_MAP: dict[int, str] = {
    0: "NO DEFINIDO",
    1: "Inscripción",
    2: "Cuota",
    3: "Derecho Examen",
    4: "Recargo",
    5: "Inscripción Seminario",
    6: "Certificación",
}

MEDIO_MAP: dict[int, str] = {
    1: "Transferencia Bancaria",
    2: "Mercado Pago",
    3: "Pago Profesor",
}

EXCLUDED_MEDIOS: set[int] = {3}

# Medium normalization aliases (sheet uses inconsistent names)
MEDIO_ALIASES: dict[str, str] = {
    "Transferencia": "Transferencia Bancaria",
}

# Add Pago Único to concept vocabulary
CONCEPT_MAP[7] = "Pago Único"  # Not in DB, generated by allocator


def map_concept(id_concepto: int, cuota_number: int | None = None) -> str:
    """Map id_concepto_pago to sheet concept name."""
    base = CONCEPT_MAP.get(id_concepto, CONCEPT_MAP[0])
    if id_concepto == 2 and cuota_number is not None:
        return f"{base} {cuota_number}"
    return base


def map_medio(id_medio: int) -> str:
    """Map id_medio_pago to sheet medio name."""
    return MEDIO_MAP.get(id_medio, "No definido")


def map_cobro_medio(id_medio: int, has_bank_movement: bool = False) -> str:
    """Map expected medio for Cobro rows.

    If the payment is backed by a bank movement, prefer the operational reality
    of the sheet: bank transfers are the canonical medio, while Mercado Pago is
    treated as secondary metadata. Pago Profesor remains unchanged.
    """
    if has_bank_movement and id_medio != 3:
        return "Transferencia Bancaria"
    return map_medio(id_medio)


def is_excluded_medio(id_medio: int) -> bool:
    """Check if this payment method should be excluded from normal flow."""
    return id_medio in EXCLUDED_MEDIOS


ESTADO_ADMINISTRATIVO_MAP: dict[int, str] = {
    -1: "No aplica",
    1: "En funciones",
    2: "De licencia",
    3: "Renunció",
    4: "Desvinculado",
    5: "Sin deuda",
    6: "Con deuda 1 mes",
    7: "Con deuda 2 meses o más",
}


def map_estado_administrativo(id_estado: int | None) -> str:
    """Map id_estado_administrativo to sheet label."""
    if id_estado is None:
        return ""
    return ESTADO_ADMINISTRATIVO_MAP.get(id_estado, "")


def normalize_medio(medio: str) -> str:
    """Normalize medium of payment name to canonical form."""
    cleaned = medio.strip()
    return MEDIO_ALIASES.get(cleaned, cleaned)
